---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: another
  image: alpine
  commands:
  - echo "Hello"
- name: save-to-file
  image: alpine
  environment:
    MY_SECRET:
      from_secret: check
  commands:
    - echo "$MY_SECRET" >> .secrets
- name: cat
  image: alpine
  commands:
    - cat .secrets
