---
kind: pipeline
type: docker
name: default

steps:
- name: greeting
  commands:
  - echo "hey"
  - ls /etc/ssl/certs
  
- name: another
  image: alpine
  commands:
  - ls /etc/ssl/certs/another.pem
  - ls /etc/ssl/certs/another2.pem
  - cat /etc/ssl/certs/another.pem
  - cat /etc/ssl/certs/another2.pem
