---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: another
  image: alpine
  commands:
  - echo "Hello"
- name: build
  image: alpine
  environment:
    USERNAME:
      from_secret: passwordmax
    PASSWORD:
      from_secret: password123
  commands:
    - echo "You can call the secrets like this examples below."
    - echo $USERNAME
    - echo $PASSWORD
    - echo "In both cases, and for security reasons, you will see asteriks '*******' instead the value under the echo command."
